[sources]
free_proxy_list = "https://free-proxy-list.net/"
ssl_proxies = "https://www.sslproxies.org/"
proxy_scrape = [
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all",
]
github_lists = [
    "https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt",
]
# optional: command producing proxy list
proxybroker_cmd = "proxybroker grab --out proxies.txt --limit 100"
