# Cargo.toml
[package]
name = "libero_validator"
version = "0.1.1"
edition = "2021"

[features]
# Enable advanced I/O stacks. Build with: `--features io_uring,ebpf,afxdp`
io_uring = ["tokio-uring"]
ebpf = ["redbpf"]
afxdp = ["afxdp"]

[dependencies]
# Async runtime & utils
tokio = { version = "1.38", features = ["full"] }
# Low‑level sockets + constant access
socket2 = "0.5"
# Optional io_uring backend
_tokio-uring = { package = "tokio-uring", version = "0.4", optional = true }
# eBPF support (optional)
redbpf = { version = "2", optional = true, default-features = false }
# Jemalloc global allocator
jemallocator = "0.5"
# Optional AF_XDP / DPDK‑style user‑space networking
afxdp = { version = "0.5", optional = true }
# TLS / session resumption
rustls = { version = "0.23", features = ["tokio"] }
# Socks + TLS wrappers
async-imap = "0.10"
async-native-tls = "0.5"
async-socks = "0.5"
# CLI
clap = { version = "4", features = ["derive"] }
once_cell = "1"
# TUI dashboard
ratatui = "0.26"
crossterm = "0.27"
# Perfect‑hash map (already used)
phf = { version = "0.11", features = ["macros"] }
# Random shuffle
rand = "0.9"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
