[lib]
name = "libero_validator"
path = "src/lib.rs"

[[bin]]
name = "libero_validator"
path = "src/main.rs"
test = false
doctest = false

[[bin]]
name = "proxy_sidecar"
path = "src/bin/proxy_sidecar.rs"
test = false
doctest = false

# Cargo.toml
# Libero Email Validator
#Tool Description: Libero Email Credential Validator (LECV)
#The Libero Email Credential Validator (LECV) is a controlled-use utility designed for legitimate, consent-based credential verification across large datasets. It is intended strictly for authorized environments such as enterprise IT operations, user-driven credential audits, breach exposure analysis, and sanctioned security research.
#Key legitimate use cases include:
#Enterprise Account Auditing: Organizations that use Libero Mail services internally can use LECV to verify employee credentials during security audits, SSO migration, or policy compliance checks. The tool is to be operated by authorized personnel only and within the bounds of internal security protocols.
#End-User Credential Health Checks: LECV allows users to voluntarily submit or load their own email and password combinations (e.g., exported from password managers) to determine whether their Libero accounts are still accessible. This helps users detect outdated, compromised, or misconfigured credentials. All operations are performed locally and do not store any sensitive data.
#Security Research & Penetration Testing: LECV may be used by certified researchers conducting credential-based testing under responsible disclosure programs or with explicit permission from the account holders or service provider. All usage must adhere to ethical hacking principles and any applicable legal frameworks.
#Breach Exposure Validation: In scenarios where credential dumps or breach datasets are discovered, LECV can be employed—under lawful authority—to validate which Libero credentials are still active. This aids in preparing exposure notifications, deactivating compromised accounts, or reporting incidents to relevant authorities. Use is restricted to environments with clear legal entitlement to act on the data.
#Important Notice:
#LECV must only be used in contexts where explicit consent, organizational ownership, or legal authority exists for all credentials tested. Unauthorized use may violate privacy laws (e.g., GDPR, CFAA, Italian Data Protection Code) and result in criminal liability.
#This tool does not store, share, or transmit any login information. All operations are designed to be performed securely, responsibly, and transparently.
#Libero Email Validator ("the Tool") checks login details for Libero email accounts for ex company employees. It tries POP3 and IMAP servers in quick succession and notes which addresses #work. It can use many network connections at once so big lists finish faster.

[package]
name = "libero_validator"
version = "0.1.1"
edition = "2021"

[features]
# Enable advanced I/O stacks. Build with: `--features io_uring,ebpf,afxdp`
io_uring = ["dep:_tokio-uring"]
ebpf = ["dep:redbpf"]
afxdp = ["dep:afxdp"]
default = []
proxyless = ["dashmap", "prometheus", "tokio-rustls", "trust-dns-resolver", "tokio-tungstenite"]
fast-open = []

[dependencies]
# Async runtime & utils
tokio = { version = "1.38", features = ["full"] }
# Low‑level sockets + constant access
socket2 = "0.5"
# Optional io_uring backend
_tokio-uring = { package = "tokio-uring", version = "0.4", optional = true }
# eBPF support (optional)
redbpf = { version = "2", optional = true, default-features = false }
# Jemalloc global allocator
jemallocator = "0.5"
# Optional AF_XDP / DPDK‑style user‑space networking
afxdp = { version = "0.4", optional = true }
# TLS / session resumption
# Socks + TLS wrappers
# CLI
# Libero Email Validator
#Tool Description: Libero Email Credential Validator (LECV)
#The Libero Email Credential Validator (LECV) is a controlled-use utility designed for legitimate, consent-based credential verification across large datasets. It is intended strictly for authorized environments such as enterprise IT operations, user-driven credential audits, breach exposure analysis, and sanctioned security research.
#Key legitimate use cases include:
#Enterprise Account Auditing: Organizations that use Libero Mail services internally can use LECV to verify employee credentials during security audits, SSO migration, or policy compliance checks. The tool is to be operated by authorized personnel only and within the bounds of internal security protocols.
#End-User Credential Health Checks: LECV allows users to voluntarily submit or load their own email and password combinations (e.g., exported from password managers) to determine whether their Libero accounts are still accessible. This helps users detect outdated, compromised, or misconfigured credentials. All operations are performed locally and do not store any sensitive data.
#Security Research & Penetration Testing: LECV may be used by certified researchers conducting credential-based testing under responsible disclosure programs or with explicit permission from the account holders or service provider. All usage must adhere to ethical hacking principles and any applicable legal frameworks.
#Breach Exposure Validation: In scenarios where credential dumps or breach datasets are discovered, LECV can be employed—under lawful authority—to validate which Libero credentials are still active. This aids in preparing exposure notifications, deactivating compromised accounts, or reporting incidents to relevant authorities. Use is restricted to environments with clear legal entitlement to act on the data.
#Important Notice:
#LECV must only be used in contexts where explicit consent, organizational ownership, or legal authority exists for all credentials tested. Unauthorized use may violate privacy laws (e.g., GDPR, CFAA, Italian Data Protection Code) and result in criminal liability.
#This tool does not store, share, or transmit any login information. All operations are designed to be performed securely, responsibly, and transparently.
#Libero Email Validator ("the Tool") checks login details for Libero email accounts for ex company employees. It tries POP3 and IMAP servers in quick succession and notes which addresses #work. It can use many network connections at once so big lists finish faster.
clap = { version = "4", features = ["derive"] }
once_cell = "1"
# Futures utilities
futures = "0.3"
libc = "0.2"
# Perfect‑hash map (already used)
phf = { version = "0.11", features = ["macros"] }
# Random shuffle
rand = "0.9"
# Bloom filter for duplicate detection
bloomfilter = "3"
# Fast CRC32 hashing
crc32fast = "1.4"
# Faster mutexes
parking_lot = "0.12"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# Proxyless mode helpers
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
dashmap = { version = "5", optional = true }
prometheus = { version = "0.13", optional = true }
tokio-rustls = { version = "0.24", optional = true }
trust-dns-resolver = { version = "0.23", default-features = false, features = ["tokio-runtime", "dns-over-https-rustls"], optional = true }
tokio-tungstenite = { version = "0.26", optional = true, features = ["rustls-tls-webpki-roots"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
anyhow = "1"
# Memory mapped input
# Libero Email Validator
#Tool Description: Libero Email Credential Validator (LECV)
#The Libero Email Credential Validator (LECV) is a controlled-use utility designed for legitimate, consent-based credential verification across large datasets. It is intended strictly for authorized environments such as enterprise IT operations, user-driven credential audits, breach exposure analysis, and sanctioned security research.
#Key legitimate use cases include:
#Enterprise Account Auditing: Organizations that use Libero Mail services internally can use LECV to verify employee credentials during security audits, SSO migration, or policy compliance checks. The tool is to be operated by authorized personnel only and within the bounds of internal security protocols.
#End-User Credential Health Checks: LECV allows users to voluntarily submit or load their own email and password combinations (e.g., exported from password managers) to determine whether their Libero accounts are still accessible. This helps users detect outdated, compromised, or misconfigured credentials. All operations are performed locally and do not store any sensitive data.
#Security Research & Penetration Testing: LECV may be used by certified researchers conducting credential-based testing under responsible disclosure programs or with explicit permission from the account holders or service provider. All usage must adhere to ethical hacking principles and any applicable legal frameworks.
#Breach Exposure Validation: In scenarios where credential dumps or breach datasets are discovered, LECV can be employed—under lawful authority—to validate which Libero credentials are still active. This aids in preparing exposure notifications, deactivating compromised accounts, or reporting incidents to relevant authorities. Use is restricted to environments with clear legal entitlement to act on the data.
#Important Notice:
#LECV must only be used in contexts where explicit consent, organizational ownership, or legal authority exists for all credentials tested. Unauthorized use may violate privacy laws (e.g., GDPR, CFAA, Italian Data Protection Code) and result in criminal liability.
#This tool does not store, share, or transmit any login information. All operations are designed to be performed securely, responsibly, and transparently.
#Libero Email Validator ("the Tool") checks login details for Libero email accounts for ex company employees. It tries POP3 and IMAP servers in quick succession and notes which addresses #work. It can use many network connections at once so big lists finish faster.
memmap2 = "0.5"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"

[dev-dependencies]
wiremock = "0.5"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread", "test-util"] }

[workspace]
members = [
    ".",
    "proxy_o_matic",
    "proxy_feed",
]

